/////////////////////////////////////////////////////////////
//                                                         //
//   WARNUNG, dies Datei wird automatisch durch            //
//   das Program "Convert_Unit_to_pas_includes" erzeugt !  //
//   Erzeugt am: 21-08-2024   19:51                        //
//                                                         //
/////////////////////////////////////////////////////////////

{$IFDEF read_interface}

procedure g_cclosure_marshal_VOID__VOID(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__VOIDv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__BOOLEAN(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__BOOLEANv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__CHAR(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__CHARv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__UCHAR(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__UCHARv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__INT(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__INTv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__UINT(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__UINTv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__LONG(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__LONGv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__ULONG(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__ULONGv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__ENUM(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__ENUMv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__FLAGS(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__FLAGSv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__FLOAT(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__FLOATv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__DOUBLE(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__DOUBLEv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__STRING(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__STRINGv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__PARAM(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__PARAMv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__BOXED(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__BOXEDv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__POINTER(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__POINTERv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__OBJECT(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__OBJECTv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__VARIANT(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__VARIANTv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__UINT_POINTER(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_VOID__UINT_POINTERv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_BOOLEAN__FLAGS(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_BOOLEAN__FLAGSv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;

//const
//  g_cclosure_marshal_BOOL__FLAGS = g_cclosure_marshal_BOOLEAN__FLAGS;  

procedure g_cclosure_marshal_STRING__OBJECT_POINTER(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_STRING__OBJECT_POINTERv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_BOOLEAN__BOXED_BOXED(closure: PGClosure; return_value: PGValue; n_param_values: Tguint; param_values: PGValue; invocation_hint: Tgpointer;
  marshal_data: Tgpointer); cdecl; external libgobject2_0;
procedure g_cclosure_marshal_BOOLEAN__BOXED_BOXEDv(closure: PGClosure; return_value: PGValue; instance: Tgpointer; args: Tva_list; marshal_data: Tgpointer;
  n_params: longint; param_types: PGType); cdecl; external libgobject2_0;
//const
//  g_cclosure_marshal_BOOL__BOXED_BOXED = g_cclosure_marshal_BOOLEAN__BOXED_BOXED;  

// === Konventiert am: 14-8-24 19:04:39 ===


{$ENDIF read_interface}


{$IFDEF read_implementation}



{$ENDIF read_implementation}
